language: node_js
os: linux
dist: focal
install:   
  - npm install -y -g typescript
  - npm install -y -g typescript@latest eslint@latest @typescript-eslint/eslint-plugin nyc
  - npm install -y -g @istanbuljs/nyc-config-typescript jest-simple-summary

script: 
  - ./scripts/build.sh